const stationsList = [
  { name: "Bahana Fm", url: "https://stream.cloudmu.id/listen/bahana_fm/stream" },
  { name: "Cosmopolitan", url: "http://stream.radiojar.com/u7d8heq3bnzuv" },
  { name: "Dahlia FM", url: "https://svara-stream.radioddns.net:8443/bandung_dahliafm" },
  { name: "dakwahsunnah", url: "http://live.dakwahsunnah.com/;" },
  { name: "Delta fm new", url: "https://rust.mrngroup.co/listen/delta_fm/delta" },
  { name: "Dengerin musik", url: "http://stream.denger.in:8888/dmi" },
  { name: "elgangga", url: "https://s1.gntr.net/radio/8010/elgangga" },
  { name: "Elshinta", url: "https://stream-ssl.arenastreaming.com:8000/jakarta" },
  { name: "female radio", url: "https://stream.cloudmu.id/listen/female/stream" },
  { name: "Gajahmada", url: "https://server.radioimeldafm.co.id/radio/8040/gajahmadafm" },
  { name: "Gen FM", url: "https://onlineradiobox.com/id/?cs=id.genjakarta&played=1" },
  { name: "inspiradio", url: "https://listen.inspiradio.id:9000/live" },
  { name: "iradio Bandung", url: "https://n0d.radiojar.com/u6ppe6hswk8uv?rj-ttl=5&rj-tok=AAABh91unGUAQWkoQMxUWz6UvQ" },
  { name: "iradio jakarta", url: "https://n08.radiojar.com/4ywdgup3bnzuv?rj-ttl=5&rj-tok=AAABh91yKPwA7435skgE5H27kQ" },
  { name: "motion radio", url: "https://cast1.my-control-panel.com/proxy/radioso2/stream" },
  { name: "OZ Bandung", url: "http://45.64.97.211:1031/;" },
  { name: "Radio BOSS", url: "https://i.klikhost.com:10914/stream/1/" },
  { name: "Radio Rodja new", url: "https://radioislamindonesia.com/rodja-low.mp3" },
  { name: "RAS fm", url: "https://i.klikhost.com/9006/stream/1/" },
  { name: "RDI", url: "http://202.147.199.99:8000/stream/1/" },
  { name: "smartfm", url: "https://cast2.my-control-panel.com/proxy/radioso3/stream" },
  { name: "TOP fm new", url: "http://streaming.topfm951.net:9510/stream/1/" },
  { name: "trax fm", url: "https://n0a.radiojar.com/rrqf78p3bnzuv?rj-ttl=5&rj-tok=AAABh9163ogAt_w8aT7VUcRuAA" },
  { name: "trijaya fm", url: "https://r.sindonews.tv/trijayafm/;stream.nsv" },
  { name: "Hard Rock", url: "https://n08.radiojar.com/7csmg90fuqruv.mp3?rj-tok=AAABh99NlQQAnnz8d1obRSB4IQ&rj-ttl=5" },
  { name: "Prambors FM", url: "https://23683.live.streamtheworld.com/PRAMBORS_FM_SC?dist=pramborsweb&pname=tdwidgets" },
  { name: "MTV Indonesia", url: "https://stream.zeno.fm/pvvz3mrtsf9uv" },
  { name: "CNN Indonesia TV", url: "http://live.cnnindonesia.com/livecnn/smil:cnntv.smil/chunklist_w275412545_b384000_sleng.m3u8" },
  { name: "Sunda Radio", url: "https://sundaradio.com/live/sundaradio" },
  { name: "Campur sari", url: "https://a8.siar.us/listen/campursari/stream" },
  { name: "V Radio", url: "http://202.147.199.100:8000/;stream.nsv" },
  { name: "Loker Musik Indonesia", url: "https://stream.lokermusik.com:8420/lokermusik" },
  { name: "NAGASWARA RADIOTEMEN Bogor", url: "https://live.nagaswarafm.com:9900/stream" },
  { name: "NAGASWARA Pop", url: "https://live.nagaswarafm.com:9100/nagaswarapop" },
  { name: "80s Radio Hits", url: "https://stream-037.zeno.fm/05eu8medd3quv?zs=nn3VmkBWSbuGUmPs4VtkyQ" },
  { name: "9020 FB FM Purwakarta", url: "https://ssg.streamingmurah.com:8434/stream" },
  { name: "Brava", url: "https://n08.radiojar.com/5k7t0rq3bnzuv?rj-ttl=5&rj-tok=AAABh-BU0xcApWHXZZl4-zR30Q" },
  { name: "City Radio Medan", url: "https://live.cityradio.id/cityradio.ogg" },
  { name: "El John FM palembang", url: "http://103.28.149.117:8032/stream" },
  { name: "Flamboyan FM", url: "https://i.klikhost.com/8236/stream" },
  { name: "Gandewa radio", url: "http://45.64.97.82:8460/;stream.nsv" },
  { name: "Gema merdeka Bali", url: "http://110.44.169.32/gema" },
  { name: "Gema FM Karawang", url: "http://stream.suararadio.com:8000/karawang_gemafm_aac" },
  { name: "Gema Surya FM", url: "https://r5.siar.us:9420/mp3.mp3?_=2" },
  { name: "Golden memories", url: "https://stream-017.zeno.fm/xg7mcgf1bf9uv?zs=URYkVB0mSMGpZ6ARx0nf6Q" },
  { name: "Global Throwback", url: "https://stream-059.zeno.fm/ehn9gybgqd0uv?zs=jIl_ZMTsRU-pJick7Otrkw" },
  { name: "Global Radio Jakarta", url: "http://202.147.199.98/;" },
  { name: "Idola fm semarang", url: "https://server.radioidola.com:8880/idolafm" },
  { name: "I-Dream Radio", url: "https://void.idserverhost.com:8010/;" },
  { name: "Imelda Radio", url: "https://server.radioimeldafm.co.id:8030/imeldafm" },
  { name: "IMI radio", url: "https://live1.indostreamserver.com:8008/stream" },
  { name: "indika fm", url: "https://s2.radio.co/sf58a82d7d/listen" },
  { name: "Irama FM", url: "http://svara-stream.radioddns.net:8000/iramafm_mono" },
  { name: "Kajian Islam", url: "https://stream-002.zeno.fm/ge2ekgd7f18uv?zs=Y3dB0G3tQ1WBU2tWIwzIJg" },
  { name: "Kisi FM", url: "http://live.serverstreaming.net:9340/kisifm" },
  { name: "Kiss FM Medan", url: "http://live.kissfm-medan.com:8080/kissfm.mp3" },
  { name: "KLCBS", url: "https://s3.vinhostmedia.com/1055/;stream" },
  { name: "Mandala FM Banyuwangi", url: "https://svara-stream.radioddns.net:8443/banyuwangi_mandalafm" },
  { name: "Megaswara Bogor", url: "http://live.mgstv.co.id:8002/1/;stream.mp3?1634215318083" },
  { name: "MFM Malang", url: "http://202.164.221.9:8222/;stream.nsv" },
  { name: "MTB FM Surabaya", url: "https://mtbfm-radio.wow.net.id:8111/;" },
  { name: "MQFM Bandung", url: "http://svara-stream.radioddns.net:8000/bandung_mqfm_mp3" },
  { name: "Menara fm", url: "https://c1.siar.us:10280/menarafmbali" },
  { name: "Media fm", url: "http://streaming.radiomediafm.com:8400/;stream.nsv" },
  { name: "Merdeka fm", url: "http://streaming.merdekafm.com:8020/;stream.nsv" },
  { name: "Muara dss", url: "https://ssg.streamingmurah.com:8668/;?1683089782130" },
  { name: "Mettaswara Dangdut", url: "https://mettaswara.com:8700/d4d" },
  { name: "Mettaswara", url: "https://mettaswara.com:8700/indo" },
  { name: "MGT FM", url: "https://s1.gntr.net/listen/mgtradio/mgtradio" },
  { name: "Medan fm", url: "https://live.medanfm.id/medanfm.ogg" },
  { name: "Niki FM", url: "https://stream-030.zeno.fm/u1mnu6ardfhvv?zs=ShKpp5NLQu-YWafm7DvTJw" },
  { name: "ONIX Radio", url: "http://u.klikhost.com:7062/;" },
  { name: "Paduka FM", url: "http://paduka.myradio.web.id:8888/padukafm?" },
  { name: "Paramuda FM", url: "http://115.178.48.43:9990/;" },
  { name: "Simfoni FM", url: "http://i.klikhost.com:9160/;rojer.mp3" },
  { name: "Radio Cosmo", url: "http://scg.streamingmurah.com:8074/stream" },
  { name: "Radio Kosmonita", url: "http://202.58.200.26:1055/live" },
  { name: "Rama FM", url: "http://rama-fm.simaya.net.id:8800/;" },
  { name: "Radio-Qu", url: "https://ssg.streamingmurah.com:8034/stream" },
  { name: "Radio muslim", url: "https://cp.phpmystream.com/radioSSLnew/s/75" },
  { name: "Radio Musik Indonesia", url: "https://stream-034.zeno.fm/727gv3qrt5quv?zs=q5wF9_yCQgy8tFIM3phRmg" },
  { name: "Radio Galuh", url: "https://stream.warawara.space/galuhfm" },
  { name: "Raka Radio indonesia", url: "http://sci.streamingmurah.com:8196/stream" },
  { name: "RRI", url: "https://stream-node0.rri.co.id/streaming/14/9014/kbrn.mp3" },
  { name: "RRI Pro 1", url: "https://stream-node1.rri.co.id/streaming/25/9025/rrijakartapro1.mp3" },
  { name: "RRI Pro 2", url: "https://stream-node1.rri.co.id/streaming/25/9025/rrijakartapro2.mp3" },
  { name: "RRI Pro 4", url: "https://stream-node1.rri.co.id/streaming/25/9025/rrijakartapro4.mp3" },
  { name: "SCFM Makassar", url: "https://a10.siar.us/radio/8030/radio.mp3" },
  { name: "Suara surabaya", url: "https://c5.siar.us:8000/stream" },
  { name: "Suara Soneta Radio", url: "https://a2.siar.us/listen/suarasoneta/radio.mp3" },
  { name: "Suara muslim surabaya", url: "http://pu.klikhost.com:8052/stream" },
  { name: "Slow radio", url: "https://stream-007.zeno.fm/dpk2zq5np2zuv?zs=Z2gdEkQNQPOAlE73nGywCw" },
  { name: "Sonora FM", url: "https://cast1.my-control-panel.com/proxy/radioso1/live" },
  { name: "Swara semarang", url: "https://server.radioimeldafm.co.id/radio/8010/swarasemarang" },
  { name: "Swara Kenanga Jogja", url: "http://51.79.167.17:7002/airtime_128" },
  { name: "Tangerang radio", url: "https://rl.tangerank.my.id/swara" },
  { name: "VIS FM", url: "http://s4.vinhostmedia.com:8000/streamaac" },
  { name: "Urban fm", url: "https://live.indostreamserver.com/8250/;" },
  { name: "Wijaya fm", url: "http://wijayafm.onlivestreaming.net:9880/stream?" },
  { name: "Z 99.9 FM", url: "https://svara-stream.radioddns.net:8443/jakarta_z999fm_aac" },
];