const stationsSource1 = [
  { name: "Bahana Fm", url: "https://s1.cloudmu.id/listen/bahana_fm/stream" },
  { name: "Most FM", url: "https://ic.mari.co.id:8443/mostfm" },
  { name: "Cosmopolitan", url: "http://stream.radiojar.com/u7d8heq3bnzuv" },
  { name: "Delta FM", url: "https://s1.cloudmu.id/listen/delta_fm/stream" }, 
  { name: "Elgangga", url: "https://b.alhastream.com:5140/radio?_ic2=1715794029661" },
  { name: "Elshinta", url: "https://stream-ssl.arenastreaming.com:8000/jakarta" },
  { name: "female radio", url: "https://stream.cloudmu.id/listen/female/stream" },
  { name: "Gajahmada FM", url: "https://server.radioimeldafm.co.id/radio/8040/gajahmadafm" },
  {name: "Gen FM 98.7 Jakarta",url: "https://ic.mari.co.id:8443/genfm"},
  { name: "Jak 101 FM", url: "https://ic.mari.co.id:8443/jakfm" },
  { name: "iradio Bandung", url: "https://n0d.radiojar.com/u6ppe6hswk8uv?rj-ttl=5&rj-tok=AAABh91unGUAQWkoQMxUWz6UvQ" },
  { name: "iradio jakarta", url: "https://n13.radiojar.com/4ywdgup3bnzuv" },
  { name: "Radio Rodja", url: "https://radioislamindonesia.com/rodja-low.mp3" },
  { name: "RAS FM", url: "https://i.klikhost.com/9006/stream/1/" },
  { name: "Radio Dangdut Indonesia", url: "https://stream.roov.id:8062/stream" },
  { name: "Trax FM", url: "https://n0a.radiojar.com/rrqf78p3bnzuv?rj-ttl=5&rj-tok=AAABh9163ogAt_w8aT7VUcRuAA" },
  { name: "Hard Rock", url: "https://n08.radiojar.com/7csmg90fuqruv.mp3?rj-tok=AAABh99NlQQAnnz8d1obRSB4IQ&rj-ttl=5" },
  { name: "Sunda Radio", url: "https://sundaradio.com/live/sundaradio" },
  { name: "Campur sari", url: "https://a8.siar.us/listen/campursari/stream" },
  { name: "80s Radio Hits", url: "https://stream-037.zeno.fm/05eu8medd3quv?zs=nn3VmkBWSbuGUmPs4VtkyQ" },
  { name: "9020 FB FM Purwakarta", url: "https://ssg.streamingmurah.com:8434/stream" },
  { name: "Brava FM", url: "https://n08.radiojar.com/5k7t0rq3bnzuv?rj-ttl=5&rj-tok=AAABh-BU0xcApWHXZZl4-zR30Q" },
  { name: "Idola fm semarang", url: "https://server.radioidola.com:8880/idolafm" },
  { name: "I-Dream Radio", url: "https://void.idserverhost.com:8010/;" },
  { name: "Kajian Islam", url: "https://stream-002.zeno.fm/ge2ekgd7f18uv?zs=Y3dB0G3tQ1WBU2tWIwzIJg" },
  { name: "Kiss FM", url: "https://ic.mari.co.id:8443/kisfm" },
  { name: "Media fm", url: "http://streaming.radiomediafm.com:8400/;stream.nsv" },
  { name: "Merdeka fm", url: "http://streaming.merdekafm.com:8020/;stream.nsv" },
  { name: "Muara dss", url: "https://ssg.streamingmurah.com:8668/;?1683089782130" },
  { name: "Mettaswara Dangdut", url: "https://mettaswara.com:8700/d4d" },
  { name: "Mettaswara", url: "https://mettaswara.com:8700/indo" },
  { name: "MGT FM", url: "https://s1.gntr.net/listen/mgtradio/mgtradio" },
  { name: "Medan fm", url: "https://live.medanfm.id/medanfm.ogg" },
  { name: "Radio Musik Indonesia", url: "https://stream-034.zeno.fm/727gv3qrt5quv?zs=q5wF9_yCQgy8tFIM3phRmg" },
  { name: "Suara surabaya", url: "https://c5.siar.us:8000/stream" },
  { name: "Suara Soneta Radio", url: "https://a2.siar.us/listen/suarasoneta/radio.mp3" },
  { name: "Swara semarang", url: "https://server.radioimeldafm.co.id/radio/8010/swarasemarang" },
          { name: "Dahlia FM", url: "https://svara-stream.radioddns.net/bandung_dahliafm" },
        { name: "HOT FM", url: "https://ic.mari.co.id:8443/hotfm" },
        { name: "Radio Budi Luhur", url: "https://onlineradiobox.com/ping/id.budiluhur" },
        { name: "Female Radio", url: "https://s1.cloudmu.id/listen/female_radio/stream" },
        { name: "Motion Radio Jakarta", url: "https://cast3.asurahosting.com/proxy/radios22/stream" },
        { name: "OZ Bandung", url: "https://streaming.ozradio.id:8443/ozbandung" },
        { name: "Radio BOSS FM", url: "https://a7.siar.us/listen/radiobossfm/stream" },
        { name: "Smart FM Jakarta", url: "https://cast2.my-control-panel.com/proxy/radioso3/stream" },
        { name: "Radio CBB", url: "https://stream01-ssl.arenastreaming.com:8056/live" },
        { name: "Trijaya FM Jakarta", url: "http://202.147.199.101:8000/;" },
        { name: "Prambors FM", url: "https://s2.cloudmu.id/listen/prambors/stream" },
        { name: "Loker Musik Indonesia", url: "https://stream.lokermusik.com/listen/lokermusik/lokermusik" },
        { name: "Flamboyan FM", url: "https://i.klikhost.com/8236/stream" },
        { name: "Gema Surya FM", url: "https://r5.siar.us:9420/mp3.mp3" },
        { name: "Smooth FM Jakarta", url: "https://svara-stream.radioddns.net/jakarta_smoothfm_mp3" },
        { name: "Global Radio Jakarta", url: "https://proxy.rctiplus.com/?name=http://111.119.207.125:8064/;" },
        { name: "Imelda FM", url: "https://server.radioimeldafm.co.id:8030/imeldafm" },
        { name: "IMI radio", url: "https://a1.siar.us/listen/imiradio/stream" },
        { name: "DFM Radio Jakarta", url: "https://i.klikhost.com/9000/stream" },
        { name: "Rama FM Bandung", url: "https://i.klikhost.com/8330/;" },
        { name: "Ardan Radio", url: "https://n13.rcs.revma.com/ugpyzu9n5k3vv?rj-ttl=5&rj-tok=AAABmRTF5-IATctJZbz5P1yUMQ" },
        { name: "Radio Cakra Bandung", url: "https://stream-156.zeno.fm/yoengdcdzyauv" },
        { name: "B Radio Bandung", url: "https://n08.rcs.revma.com/9yp8b9pd6k3vv" },
        { name: "Megaswara Bogor", url: "https://server.adyadigitalteknologi.com:8010/1" },
        { name: "Pop FM", url: "https://i.klikhost.com/8272/stream" },
        { name: "Radio Muara", url: "http://45.64.97.82:8778/;" },
        { name: "MQFM Bandung", url: "https://mqfmstreaming.kamil.web.id/;" },
        { name: "Paramuda FM", url: "https://i.klikhost.com/8332/;" },
        { name: "9020 FB FM Purwakarta", url: "https://ssg.streamingmurah.com:8434/stream" },
        { name: "PASS FM Bandung", url: "https://stream-174.zeno.fm/w70fp14bs18uv" },
        { name: "Radio CMN", url: "https://stream.coolkas.com/radio/8160/radiocmn" },
        { name: "KISI FM", url: "https://live.kisifm.com/listen/kisifm/kisifm" },
        { name: "Simfoni FM", url: "http://i.klikhost.com:9160/;rojer.mp3" },
        { name: "Radio Cosmo", url: "http://scg.streamingmurah.com:8074/stream" },
        { name: "Mendhut FM", url: "http://c4.siar.us:8790/stream" },
        { name: "KIS FM Semarang", url: "http://123.255.201.126:8020/kisfm" },
        { name: "Radio Idola Semarang", url: "https://stream.radioidola.com/listen/idolafm/live" },
        { name: "Radio Galuh", url: "https://stream.yaomiakba.com/galuhfm" },
        { name: "Raka FM", url: "https://cast2.my-control-panel.com/proxy/radioso5/stream" },
        { name: "RRI Pro 1 Jakarta", url: "https://stream-node1.rri.co.id/streaming/25/9025/rrijakartapro1.mp3" },
        { name: "RRI Pro 2 Jakarta", url: "https://stream-node1.rri.co.id/streaming/25/9025/rrijakartapro2.mp3" },
        { name: "RRI Pro 3 Yogyakarta", url: "https://stream-node0.rri.co.id/streaming/14/9014/kbrn.mp3" },
        { name: "RRI Pro 4 Jakarta", url: "https://stream-node1.rri.co.id/streaming/25/9025/rrijakartapro4.mp3" },
        { name: "Suara Giri FM", url: "http://streaming.girifm.com:8010/;" },
        { name: "Hits Memories", url: "https://onlineradiobox.com/ping/id.hitsmemories" },
        { name: "Sonora FM Jakarta", url: "https://cast1.my-control-panel.com/proxy/radioso1/live" },
        { name: "Gen FM Surabaya", url: "https://ic.mari.co.id:8443/gensbyfm" },
        { name: "Tangerang radio", url: "https://rl.tangerank.my.id/swara" },
        { name: "Urban FM Bandung", url: "https://a1.siar.us/listen/urbanradio/stream" },
        { name: "Wijaya FM", url: "http://wijayafm.onlivestreaming.net:9880/stream?" },
        { name: "Z 99.9 FM", url: "https://svara-stream.radioddns.net/jakarta_z999fm_aac" },
];